basePath: /
info:
    description: 'Title: Post API'
    title: Post API
    version: 0.0.1
paths:
    /configurations/:
        post:
            description: Add new configuration
            operationId: createConfigration
            parameters:
                - description: 'name: body'
                  in: body
                  name: body
                  required: true
                  schema: {}
                  x-go-name: Body
            responses:
                "201":
                    $ref: '#/responses/ResponsePost'
                "400":
                    $ref: '#/responses/ErrorResponse'
                "500":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - post
    /configurations/{id}/{version}:
        delete:
            description: Delete configuration
            operationId: deleteConfiguration
            parameters:
                - description: Configuration ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
            responses:
                "204":
                    $ref: '#/responses/NoContentResponse'
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - post
        get:
            description: Get configuration by ID
            operationId: getConfigurationById
            parameters:
                - description: Configuration ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
            responses:
                "200":
                    $ref: '#/responses/ResponsePost'
                "404":
                    $ref: '#/responses/ErrorResponse'
                "500":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - post
    /group/:
        post:
            description: Add new configuration group
            operationId: createConfigrationGroup
            parameters:
                - description: 'name: body'
                  in: body
                  name: body
                  required: true
                  schema: { }
                  x-go-name: Body
            responses:
                "200":
                    $ref: '#/responses/ResponsePost'
                "400":
                    $ref: '#/responses/ErrorResponse'
                "500":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - post
    /group/{id}/{version}:
        delete:
            description: Delete group
            operationId: deleteGroup
            parameters:
                - description: Group ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
            responses:
                "204":
                    $ref: '#/responses/NoContentResponse'
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - post
        get:
            description: Get group by ID
            operationId: getGroupById
            parameters:
                - description: Group ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
            responses:
                "200":
                    $ref: '#/responses/ResponsePost'
                "404":
                    $ref: '#/responses/ErrorResponse'
                "500":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - post
    /group/{id}/{version}/extend:
        post:
            description: Extend configuration group
            operationId: extendConfigurationGroup
            parameters:
                - description: 'name: body'
                  in: body
                  name: body
                  descrition: Id of the configuration group to extend
                  required: true
                  schema: { }
                  x-go-name: Body
            responses:
                "200":
                    $ref: '#/responses/ResponsePost'
                "400":
                    $ref: '#/responses/ErrorResponse'
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - post
produces:
    - application/json
responses:
    ErrorResponse:
        description: ""
        headers:
            message:
                description: |-
                    Message of the error
                    in: string
                type: string
            status:
                description: |-
                    Error status code
                    in: int64
                format: int64
                type: integer
    NoContentResponse:
        description: ""
    ResponsePost:
        description: ""
        headers:
            id:
                description: |-
                    Id of the post
                    in: string
                type: string
            tags:
                description: |-
                    List of tags of the post
                    in: []string
                items:
                    type: string
                type: array
            text:
                description: |-
                    Text content of the post
                    in: string
                type: string
            title:
                description: |-
                    Title of the post
                    in: string
                type: string
schemes:
    - http
swagger: "2.0"
