name: alati

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  docker:
    runs-on: windows-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: alatizarazvojsoftvera2023-projekat-app
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alatizarazvojsoftvera2023-projekat-app:latest
